name: rigel
description: A CHIP-8 interpreter made with flutter
version: 1.0.0
repository: https://github.com/TheYautja/Rigel

flutter:
  assets:
    - roms/games/Cave.ch8

environment:
  sdk: ^3.11.0

# Add regular dependencies here.
dependencies:
  flame: ^1.36.0
  path: ^1.9.0
  raylib: ^0.3.0
  window_size: ^0.1.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
